### ISSUE TITLE
Question: Data preparation & Format

### ISSUE THREAD

**Issue by jmandel1027** [go-spatial/tegola-bathymetry#1]
This is a super interesting case study, thanks for putting it together. I wanted to experiment with this configuration as well as the Open Sea Map tegola configuration as well but had two questions:

1. Regarding the GEBCO dataset, it's a netCDF grid correct? do you have any docs on inserting the gridded dataset to postgis? I've been playing around and the only ideas that come to mind at the moment is to use something like gdal_translate to convert the netCDF data to raster and then insert that to postgis with ogr2ogr. Just trying to get the example off the ground.

2. In the open sea map configuration I was curious as to why it is preferable to split up the various data sources into disparate DBs? Is it because the datasets are too beefy? or is it more for admin / data separation of concerns.

Thanks again!

**Comment by erictheise** [comment]
Thanks for your interest in this project @jay-manday.

Regarding your first question, I'd say you're on the right track. I took a lot of inspiration from Anthony Lukach's [README for his `vector-ocean`](https://github.com/alukach/vector-ocean) which outlines the use of the same tools you mention.

To answer your second question, I had many simultaneous Tegola projects going at the same time; these planet-sized ones and some personal ones that were based on metro extracts and Geofabrik country extracts. If I remember correctly the scripts in the core Tegola repo would do a brute import of Natural Earth, OSM land and water polygons, maybe another source or two during the creation of a project. I couldn't afford the time or space to duplicate those sources for six or eight simultaneous projects so I set them up as separate data sources. The data was never modified unless an upgrade became available and then it seemed easier to update since it was siloed in its own database. I seem to recall that we needed to have different versions of Natural Earth running after they released a new version and I almost certainly used my Natural Earth data for non-Tegola projects, too.

I'll also answer a question you didn't ask. When I started working on the [OpenSeaMap clone](https://github.com/go-spatial/tegola-openseamap) I didn't have very much experience with Tegola (no one did, really, it was still at version 0.3 or 0.4) and I had no experience with the `seamark` tagging scheme. You'll find dozens of explicit queries for seamark entities; this helped me and Gretchen learn about the data and the nuances of nautical charting. Given what we were doing – a cartographic proof of concept – pounding on the database like that was acceptable. You'll want to look into refactoring/consolidating those queries when you experience performance issues.

Been two years! Hope that helps!

**Comment by jmandel1027** [comment]
Hey @erictheise thanks for taking to the time for the thoughtful answer!

Awesome, thanks for passing that readme along, that is super super helpful on my end and does a great job explaining more of the nuances and process for burning the gridded data to raster and so on.

Regarding the data sources that totally makes sense, given the static nature of that data, the only other alternative i had thought of was to add datasource registry table and insert a registry id when seeding the db. Though as you mentioned, it is probably more trouble than it's worth, esp when the next update rolls around.

Also thanks for the warning re: pounding the db, I'll keep that in mind! Maybe in the mean time i can fry my breakfast burrito on my cpu and kill two birds w/ one stone.

Thanks again

**Comment by erictheise** [comment]
Hope you didn't burn your burrito, @jay-manday. Happy to try and answer any future questions but I'm going to close this issue.
